winstonjs/winston-mongodb

lib/winston-mongodb.js
There is a possibility to close all logger transports using Logger.close method. That is useful for manual releasing of transports' resources, like MongoDB connection in this case. Original implementation did not provide close method usable by winston's Logger => we encountered process hanging up and not finishing due to opened MongoDB connection after finishing its execution.
=> Closing transport using Logger.close

README.md, lib/winston-mongodb.js
Removes color attributes from log messages before storing them in
MongoDB. (Issue #62)
=> Decolorize log messages

lib/helpers.js
Was running into an issue with `hasOwnProperty`:
```
TypeError: object.hasOwnProperty is not a function
at cleanFieldNames (/.../node_modules/winston-mongodb/lib/helpers.js:41:17)
at cleanFieldNames (/.../node_modules/winston-mongodb/lib/helpers.js:56:7)
at cleanFieldNames (/.../node_modules/winston-mongodb/lib/helpers.js:56:7)
at Object.exports.prepareMetaData (/.../node_modules/winston-mongodb/lib/helpers.js:18:5)
at /.../node_modules/winston-mongodb/lib/winston-mongodb.js:263:28
at Db.collection (/.../node_modules/mongodb/lib/db.js:449:20)
at /.../node_modules/winston-mongodb/lib/winston-mongodb.js:253:16
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```
Seems to be caused by a change in Node v6:
- …
=> Use hasOwnProperty from Object prototype (Node v6.x)

lib/helpers.js
when logging an object with key that contains multiple dots - mongo will throw and error because current code only substitutes the first dot or $.
```json
{
"a.b.c": "abc" //will be translated to "a[dot]b.c" --> will cause mongo error
}
```
replace now gets a regex to replace all dot and $ instances.
=> cleanFieldNames replaces dots and dollar characters globally

lib/winston-mongodb.js
In createCollection method, remove dropIndex method.
createCollection is called only the first time when collection is not exist, so index is already not found.
=> dropIndex removed

lib/winston-mongodb.js
1. checking if index parameters have changed before dropping
1. index is created in background, otherwise it can hang the db (for large collection) until creation is finished
=> Check index params before drop

lib/helpers.js
See issue #85
Adds a check so that `ObjectID`s will be serialized correctly as strings.
=> Fix ObjectID serialization issue

README.md, lib/winston-mongodb.js, package.json
MongoClient.connect now using flat options structure - http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html
If 'old' style options used, mongodb client logs deprecated warnings to console.
=> Flat options structure in MongoClient.connect

lib/helpers.js
Fixes winstonjs/winston-mongodb#98
=> Preserve Arrays during circular reference removal

lib/winston-mongodb.d.ts
Latest type definitions were not consumable by ts due to missing extends of base Winston interfaces.
=> fixed type definitions

lib/winston-mongodb.d.ts
Error: When attempting to transpile a typescript@2.9.2 project importing winston@3.0.0 & `winston-mongodb@4.0.3, we get the following TypeScript errors:
```node_modules/winston-mongodb/lib/winston-mongodb.d.ts(6,10): error TS2305: Module '"/Users/keith.gillette/Code/TaskTrain/node_modules/winston/index"' has no exported member 'TransportInstance'.
node_modules/winston-mongodb/lib/winston-mongodb.d.ts(6,41): error TS2305: Module '"/Users/keith.gillette/Code/TaskTrain/node_modules/winston/index"' has no exported member 'TransportOptions'.```
=> Remove undefined exporter members

README.md
As written, the example throws a 'Invalid transport, must be an object with a log method.' error.
=> docs: fix incorrect usage

README.md
Currently the documention is not clear as to what type of object the `db` option is expecting. In version `3.0.0` a preconnected `Db` object was accepted, but since `4.0.0`, a `MongoClient` is accepted instead.
=> Fix documentation relating to db option

lib/winston-mongodb.js
I'm running NodeJS v6.14.3 and have just updated to winston v3.0.0 and winston-mongodb 4.0.3.
When I try to initialize the mongodb transport I get the following error and then the process exits:
```
node_modules/winston-mongodb/lib/winston-mongodb.js:100
SyntaxError: Unexpected token )
```
Trailing commas in function calls are not supported in NodeJS < v8 and crashes the process upon transport initialization.
Removing comma.
=> Removing trailing comma in function call

README.md, lib/winston-mongodb.js
In `wintson@3` there is no more `meta` key by default inside the `info` object in `winston@3`. It could be added with `formatters`, but the `metadata` formatter now stores it as `metadata` instead of `meta` by default.
=> Allow configuring of metadata key

lib/winston-mongodb.d.ts
This contains two changes:
1. Make the constructor inline with transports.StreamTransportInstance such that options can be null/undefined. This fixes type-hinting on the constructor.
2. Make it easier to import/define the MongoDB transport in a downstream project.
As pointed out in https://github.com/winstonjs/winston-mongodb/issues/152#issuecomment-473873531, it's pretty convoluted to use the typings.
Adding this change allows one to more simply use:
```typescript
import { MongoDB } from 'winston-mongodb';
let a = new MongoDB({
"db": "test"
});
```
The `winston.transports.MongoDB` typing still doesn't work, but I'm not sure how to fix that. This at least follows a similar approach though as the winston-daily-rotate-file in exporting a concrete usage of the TransportInstance to use …
=> Make it easier to use typescript typing

lib/winston-mongodb.d.ts
This PR provides a fix for the type definitions which is not extending the transports interface.
Also for #183 typescript compatibility
=> fix: type definition not extending winston.transports

README.md, lib/winston-mongodb.d.ts, lib/winston-mongodb.js, package-lock.json, test/winston-mongodb-test.js
Adding support for using a different DB name than the default one from the connection URI.
The use case is to allow users to use log with a pre-connected mongo client, but use a different name than the default.
=> adding option to set the DB name

.gitignore, README.md, lib/winston-mongodb.d.ts, lib/winston-mongodb.js, package-lock.json, package.json, test/winston-mongodb-test.js
1. added `dotenv` as dev-dependency for easier testing
2. originally I wanted to fix dts too, so it won't be necessary to provide Promise with connected mongo-client, but left it as it is
3. fixed (I hope I understood your intention correctly) metadata storing - winston sends whole info object and metadata is everything besides label and message
4. fixed metadata key - you could provide a new name as an option, but was stored always as `meta`
=> Fixing metadata storing

lib/helpers.js, test/helpers-test.js
I was facing an issue where winston-mongodb didn't properly remove dots from object keys in metadata. It turns out that these object keys were inside an object with `null` prototype, which therefore returns `false` for an `instanceof Object` check.
Before performing the actual code change, I added a bunch of tests to safeguard the existing functionality.
=> Properly handle objects with null prototype in metadata

.eslintrc, .github/workflows/ci.yml, lib/helpers.js, lib/winston-mongodb.js, package-lock.json, package.json, test/helpers-test.js, test/winston-mongodb-test.js
See https://github.com/winstonjs/winston-mongodb/issues/225.
I strongly suggest going commit by commit.
My approach to the linting fixes:
- Disable rules that don't seem to fit the project well
- Fix at least all errors
- Keep some warnings around as "things we may want to fix at a later time". These show up as warnings in VS Code and in GitHub Actions, but they don't block the pipeline.
- It may make sense to disable some of these as well (complexity, max statements) but I'm not sure.
=> Make CI work (resolves #225)

README.md, lib/helpers.js, lib/winston-mongodb.js, package-lock.json, package.json, test/helpers-test.js, test/winston-mongodb-test.js
see #218 
Changes done:
- bump mongodb to 6.5.0
- updated mongo config
@DABH can you please have a look at this PR
=> Bump mongodb to 6.5.0
